name: ci-cd pipline

on: [push]
  
jobs:
  build-express-login-logout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci

      - name: Start server
        run: npm start & sleep 5

      - name: Run tests
        run: npm test & sleep 5
